EIP and volume feature (ecs create)  - fix some race conditions  - some further checks / log output

diff --git a/otc b/otc
--- a/otc
+++ b/otc
@@ -1,4 +1,5 @@
 #!/bin/bash
+#[ "$1" = -x ] && shift && set -x
 # vi:set ts=3 sw=3:
 # == Module: Open Telekom Cloud Cli Interface 0.6.x
 #
@@ -1089,8 +1090,9 @@ ECSAttachVolumeListName() {
 
 ECSAttachVolumeName() {
 	local server_name="$1" dev_vol="$2" ecsid volid
-	ecsid=$(getECSList |  while read id name  ; do [ "$name" = "$server_name"  ] && echo $id && break; done)
-	volid=$(getEVSList |  while read id name x; do [ "$name" = "${dev_vol#*:}" ] && echo $id && break; done)
+	ecsid=$(getECSList |  while read id name  ; do [ "$name" = "$server_name"  -o "$id" = "$server_name"  ] && echo $id && break; done)
+	volid=$(getEVSList |  while read id name x; do [ "$name" = "${dev_vol#*:}" -o "$id" = "${dev_vol#*:}" ] && echo $id && break; done)
+	[ -z "$volid" ] && echo "$ERROR: volume '${dev_vol#*:}' doesn't exist" >&2 && return 1
 	ECSAttachVolumeId  "$ecsid"  "${dev_vol%:*}:$volid"
 }
 
@@ -1398,18 +1400,24 @@ PUBLICIPSDelete() {
 	curldeleteauth "$TOKEN" "$AUTH_URL_PUBLICIPS/$@" | jq '.[]'
 }
 
+getPRTID() {
+	(  VM=$1; getECSVM | sed -n '/^\[/,/^\]/p' \
+	   | jq '.[] | .port_state + ";" + .fixed_ips[0].ip_address + ";" + .port_id' | tr -d \" \
+	   | while IFS=\; read state ip port; do [ "$state" = ACTIVE ] && [ "$ip" != "" ] && echo $port;done)
+}
+
 BindPublicIpToCreatingVM() {
-	ECSID=$(getECSJOBList $ECSSUBTASKID | jq '.entities.server_id' | sed 's/"//g')
-	##### use this ecs server id to attach volumes, external ip_addresses, ...
-	PRTID=$(VM=$ECSID; getECSVM | sed -n '/^\[/,/^\]/p' \
-	        | jq '.[] | .port_state + ";" + .fixed_ips[0].ip_address + ";" + .port_id' | tr -d \" \
-	        | while IFS=\; read state ip port; do [ "$state" = ACTIVE ] && [ "$ip" != "" ] && echo $port;done)
+	##### use ecs server id to attach volumes, external ip_addresses, ...
+	while [ -z "$PRTID" ]; do sleep 5; PRTID=$(getPRTID $ECSID);done
 	##### input: $EIP
-	EIPID=$(getPUBLICIPSList | sed 's/  /;/g' | while IFS=";" read id eip iip status bid b type;do
-	        [ "$eip" = "$EIP" ]||[ "$id" = "$EIP" ]||continue
-	        [ "$status" = "DOWN" ] && echo "$id"
-	        echo "ERROR: requested external IP is of wrong status: $status" >&2)
-	PUBLICIPSBind "$ECSID" "$PRTID"
+	EIPID=$(getPUBLICIPSList | sed 's/   /;/g' \
+          |  while IFS=";" read id eip iip status bid b type;do
+	                [ "$eip" = "$EIP" ]||[ "$id" = "$EIP" ]|| continue
+	                [ "$status" = "DOWN" ] && echo "$id"   && break
+	                echo "ERROR: requested external IP is of wrong status: $status" >&2
+                done)
+	[ -n "$EIPID" ] && PUBLICIPSBind "$EIPID" "$PRTID" \
+	|| return 1
 }
 
 PUBLICIPSBind() {
@@ -1801,12 +1809,14 @@ elif [ "$MAINCOM" == "ecs" ] && [ "$SUBCOM" == "create" ]; then
 
    if [ "$NUMCOUNT" = 1 ]; then
       WaitForSubTask $ECSTASKID 10    ##### => generate $ECSSUBTASKID (to get server_id=ECSID)
-      [ -n "$EIP"     ] && BindPublicIpToCreatingVM
-      [ -n "$DEV_VOL" ] && ECSAttachVolumeListName
+      ECSID=null
+      while [ "$ECSID" = null ]; do sleep 10; ECSID=$(getECSJOBList $ECSSUBTASKID | jq '.entities.server_id' | sed 's/"//g');done
+      [ -n "$EIP"     ] && BindPublicIpToCreatingVM || echo "ERROR binding external IP $EIP" >&2
    fi
 
    WaitForTask $ECSTASKID 10
    echo "ECS Creation status: $ECSCREATEJOBSTATUS"
+   [ "$NUMCOUNT" = 1 ] && [ -n "$DEV_VOL" ] && ECSAttachVolumeListName "$ECSID" "$DEV_VOL"
    if [ "$ECSCREATEJOBSTATUS" != "SUCCESS" ];then
 	exit 1
    fi
