otc-tools-v0.6.11:
New command line options for VM (ECS) creation:
  --wait/--nowait, --volumetype, --bandwidth
Defaults for VOLUMETYPE
Derive AZ from subnet's AZ and check consistency
Default count to 1 if nothing specified in ECS creation
Optional --soft/--hard for ECS actions (reboot etc.)
Document debug option in help message
Only warn if s3 is missing, don't abort
Fix otc ecs job <TASKID>

diff --git a/otc b/otc
--- a/otc
+++ b/otc
@@ -54,6 +54,7 @@ else
 	echo "Warning: No ~/.otc_env.sh found, no defaults for ECS creation"
 	if test -z "$OS_USERNAME"; then
 		test -e ~/novarc && source ~/novarc
+		test -e ~/.novarc && source ~/.novarc
 		test -e ~/.ostackrc && source ~/.ostackrc
 	fi
 fi
@@ -102,11 +103,15 @@ curlgetauth()
 	curl $INS -sS -X GET -H "Accept: application/json" -H "X-Auth-Token: $TKN" "$@"
 }
 
+unset SUBNETAZ
+
 ##########################################################################################
 
 
 
 #FUNCTIONS ###############################################################################
+
+# TODO: Token caching ...
 
 getIamToken() {
 	if test -n "$OS_PROJECT_ID"; then
@@ -261,8 +266,10 @@ find_id()
 convertSUBNETNameToId() {
 	#curlgetauth $TOKEN "$AUTH_URL_SUBNETS?limit=160"
 	#SUBNETID=`curlgetauth $TOKEN "$AUTH_URL_SUBNETS" | jq '.subnets[] | select(.name == "'$SUBNETNAME'") | .id' | tr -d '" ,'`
-	SUBNETID=`curlgetauth $TOKEN "$AUTH_URL_SUBNETS?limit=160" | find_id subnets "$SUBNETNAME"`
-	export SUBNETID
+	SUBNETS=`curlgetauth $TOKEN "$AUTH_URL_SUBNETS?limit=160"`
+       	SUBNETID=`echo "$SUBNETS" | find_id subnets "$SUBNETNAME"`
+	SUBNETAZ=`echo "$SUBNETS" | find_id subnets "$SUBNETNAME" name availability_zone`
+	export SUBNETID SUBNETAZ
 }
 
 
@@ -331,26 +338,31 @@ printHelp() {
    echo "otc ecs vm <id>                show instance <id>"
    echo "otc ecs create -n <name>       create ecs instance <name>"
    echo "otc ecs create --count 1  --public true --file1 /tmp/a=/otc/a		create vm with public ip and attach file from local drive /tmp/a to VM drive /otc/a directory"    
-   echo "otc ecs create --instance-type <FLAVOR> --instance-name <NAME> --image-name <IMAGE> --subnet-name <SUBNET> --vpc-name <VPC> --security-group-name <SGNAME> --admin-pass <PASSWD> --key-name <SSHKEYNAME> --public <true/false> --disksize <DISKGB>"
-   echo "otc ecs reboot-instances <id>  reboot ecs instance <id>"
-   echo "otc ecs stop-instances <id>    stop ecs instance <id>"
+   echo "otc ecs create --instance-type <FLAVOR> --instance-name <NAME> --image-name <IMAGE> --subnet-name <SUBNET> --vpc-name <VPC> --security-group-name <SGNAME> --admin-pass <PASSWD> --key-name <SSHKEYNAME> --public <true/false> --bandwidth <BW> --disksize <DISKGB> --disktype SATA|SAS|SSD --az <AZ> --[no]wait"
+   echo "otc ecs reboot-instances <id>  reboot ecs instance <id>, optionally --soft/--hard"
+   echo "otc ecs stop-instances <id>    stop ecs instance <id>, dito"
    echo "otc ecs start-instances <id>   start ecs instance <id>"
-   echo "otc ecs job <id>               show status of job <id>"
    echo "otc ecs delete <id> <id> ...   delete VM along with EIPs"
+   echo "otc ecs job <id>               show status of job <id>"
+   echo "otc keypair list               list ssh key pairs"
+   echo
    echo "otc evs list                   list all volumes"
+   echo
    echo "otc vpc list                   list all vpc"
+   echo "otc vpc create --vpc-name <vpcname> --cidr <cidr>     create vpc "
    echo "otc subnet list                list all subnet"
    echo "otc security-group list        list all security-group"
    echo "otc security-group-rules list <group-id>     show rules of security group <group-id>"
-   echo "otc keypair list               list ssh key pairs"
-   echo "otc vpc create --vpc-name <vpcname> --cidr <cidr>     create vpc "
    echo "otc security-group create -g <groupname> --vpc-name <vpc name> create security group" 
    echo "otc subnet create --subnet-name <subnetname> --cidr <cidr> --gateway-ip <gateway> --primary-dns <primary-dns> --secondary-dns <sec-dns> --availability-zone <avalibility zone> --vpc-name <vpcname>"
    echo "otc security-group-rules create --security-group-name <secgroupname> --direction <direction> --protocol <protocol: tcp, udp, icmp> --ethertype <ethtype: IPv4,IPv6>  --portmin <port min> --portmax <portmax>"
+   echo
    echo "otc images list                list all images"
    echo "otc images show <id>           show image details"
+   echo
    echo "otc iam token                  generate a new iam token"
-   echo ""
+   echo
+   echo "otc debug CMD1 CMD2 PARAMS	for debugging ..."
 }
 
 
@@ -424,8 +436,24 @@ ECSCreate() {
 	else
 		unset DISKSIZE
 	fi
+	if [ -z "$VOLUMETYPE" ]; then VOLUMETYPE="SATA"; fi
 
-	OPTIONAL=""	
+	if test -z "$BANDWIDTH"; then BANDWIDTH=25; fi
+
+	if test -z "$AZ"; then
+		if test -n "$SUBNETAZ"; then
+			AZ="$SUBNETAZ"
+		else
+			echo "Need to specify AZ (or derive from subnet)"
+			exit 2
+		fi
+	fi
+	if test -n "$SUBNETAZ" -a "$SUBNETAZ" != "$AZ"; then
+		echo "ERROR: AZ ($AZ) must match subnets AZ ($SUBNETAZ)"
+		exit 2
+	fi
+
+	OPTIONAL=""
 	if [ "$CREATE_ECS_WITH_PUBLIC_IP" == "true" ]; then
 		# TODO: have to got from param 
 		OPTIONAL="$OPTIONAL
@@ -433,7 +461,7 @@ ECSCreate() {
 			\"eip\": { 
 				\"iptype\": \"5_bgp\", 
 				\"bandwidth\": { 
-					\"size\": 25, 
+					\"size\": $BANDWIDTH, 
 					\"sharetype\": \"PER\", 
 					\"chargemode\": \"traffic\" 
 				} 
@@ -450,6 +478,7 @@ ECSCreate() {
 		\"adminPass\": \"$ADMINPASS\","
 	fi
 	#OPTIONAL="$OPTIONAL \"__vnckeymap\": \"en\","
+	if test -z "$NUMCOUNT"; then NUMCOUNT=1; fi
 
 	REQ_CREATE_VM='{
 	    "server": {
@@ -465,7 +494,7 @@ ECSCreate() {
 		"security_groups": [ { "id": "'"$SECUGROUP"'" } ],
 		"nics": [ { "subnet_id": "'"$SUBNETID"'" } ],
 		'"$OPTIONAL"'
-		"count": "'"$NUMCOUNT"'"
+		"count": '$NUMCOUNT'
 	    }
 	}'
 	
@@ -635,27 +664,13 @@ SECGROUPRULECreate() {
 
 # Package dependency #####################################################################
 # check libs3 installed 
-command -v s3 >/dev/null 2>&1 || { echo -n>&2 "OTC requires libs3 package to be installed. 
-Please run following command: 
-Fedora: 
-  sudo yum install libs3 
-Debian:
-  apt-get install libs3 
-SUSE:
-  zypper install libs3-2
-to install neccesary component.
-Aborting."; exit 1; }
+command -v s3 >/dev/null 2>&1 || { echo -n>&2 "OTC requires libs3 package to be installed for object storage operations. 
+Please install libs3 or libs3-2 using yum/apt-get/zypper.
+Continuing anyway ..."; }
 
 # check jq installed 
 command -v jq >/dev/null 2>&1 || { echo -n>&2 "OTC requires jq package to be installed.
-Please run following command: 
-Fedora: 
-  sudo yum install jq
-Debian:
-  apt-get install jq
-SUSE:
-  zypper install jq
-to install neccesary component.
+Please install jq  using yum/apt-get/zypper.
 Aborting."; exit 1; }
 
 ##########################################################################################
@@ -754,7 +769,7 @@ case $key in
     SECDNS="$2"
     shift # past argument
     ;;
-    -z|--availability-zone)
+    -z|--availability-zone|--az)
     AZ="$2"
     shift # past argument
     ;;
@@ -768,6 +783,10 @@ case $key in
     ;;
     -p|--public)
     CREATE_ECS_WITH_PUBLIC_IP="$2"
+    shift # past argument
+    ;;
+    --disktype)
+    VOLUMETYPE="$2"
     shift # past argument
     ;;
     --disksize)
@@ -797,6 +816,22 @@ case $key in
     --key-name)
     KEYNAME="$2"
     shift # past argument
+    ;;
+    --bandwidth)
+    BANDWIDTH=$2
+    shift # past argument
+    ;;
+    --wait)
+    WAIT_CREATE="true"
+    ;;
+    --nowait)
+    WAIT_CREATE="false"
+    ;;
+    --hard)
+    ECSACTIONTYPE="HARD"
+    ;;
+    --soft)
+    ECSACTIONTYPE="SOFT"
     ;;
 
     --default)
@@ -842,19 +877,19 @@ elif [ "$MAINCOM" == "ecs" -a "$SUBCOM" == "show" ] ||
 elif [ "$MAINCOM" == "debug" ]; then
    getIamToken 
 
-   if [ "$VPCNAME" != "" ];then convertVPCNameToId; fi
-   if [ "$SUBNETNAME" != "" ];then convertSUBNETNameToId; fi 
-   if [ "$IMAGENAME" != "" ];then convertIMAGENameToId; fi
-   if [ "$SECUGROUPNAME" != "" ];then convertSECUGROUPNameToId; fi
+   if [ "$VPCNAME" != "" ]; then convertVPCNameToId; fi
+   if [ "$SUBNETNAME" != "" ]; then convertSUBNETNameToId; fi 
+   if [ "$IMAGENAME" != "" ]; then convertIMAGENameToId; fi
+   if [ "$SECUGROUPNAME" != "" ]; then convertSECUGROUPNameToId; fi
    echo -e "Image : $IMAGENAME: $IMAGE_ID\nVPC   : $VPCNAME: $VPCID\nSubnet: $SUBNETNAME: $SUBNETID\nSecGrp: $SECUGROUPNAME: $SECUGROUP"
 
 elif [ "$MAINCOM" == "ecs" ] && [ "$SUBCOM" == "create" ];then
    getIamToken 
 
-   if [ "$VPCNAME" != "" ];then convertVPCNameToId; fi
-   if [ "$SUBNETNAME" != "" ];then convertSUBNETNameToId; fi 
-   if [ "$IMAGENAME" != "" ];then convertIMAGENameToId; fi
-   if [ "$SECUGROUPNAME" != "" ];then convertSECUGROUPNameToId; fi
+   if [ "$VPCNAME" != "" ]; then convertVPCNameToId; fi
+   if [ "$SUBNETNAME" != "" ]; then convertSUBNETNameToId; fi 
+   if [ "$IMAGENAME" != "" ]; then convertIMAGENameToId; fi
+   if [ "$SECUGROUPNAME" != "" ]; then convertSECUGROUPNameToId; fi
    
    ECSCreate "$NUMCOUNT" "$INSTANCE_TYPE" "$IMAGE_ID" "$VPCID" "$SUBNETID" "$SECUGROUP"
    echo "$ECSTASKID"
@@ -867,7 +902,7 @@ echo "JOBID:   $AUTH_URL_ECS_JOB"
 	   printf "#"
 	   while [ "$ECSCREATEJOBSTATUS" == "RUNNING" ] || [ "$ECSCREATEJOBSTATUS" == "INIT" ]
 	   do
-	      sleep 5
+	      sleep 10
 	      getECSJOBList
 	      echo -n "#"	    
 	   done
@@ -913,10 +948,10 @@ elif [ "$MAINCOM" == "ecs" ] && [ "$SUBCOM" == "stop-instances" ];then
    getIamToken 
    ECSAction
 elif [ "$MAINCOM" == "ecs" ] && [ "$SUBCOM" == "job" ];then
+   getIamToken
    ECSTASKID=$1
    export AUTH_URL_ECS_JOB="https://ecs.eu-de.otc.t-systems.com/v1/$OS_PROJECT_ID/jobs/$ECSTASKID"
-#   echo $AUTH_URL_ECS_JOB
-   getIamToken 
+   #echo $AUTH_URL_ECS_JOB
    getECSJOBList
 elif [ "$MAINCOM" == "ecs" -a "$SUBCOM" == "delete" ]; then
    getIamToken
