Support Huawei image create+upload combo call.

diff --git a/otc b/otc
--- a/otc
+++ b/otc
@@ -330,6 +330,7 @@ getIamToken() {
 
 	AUTH_URL_IMAGES="${BASEURL/iam/ims}/v2/images"
 	AUTH_URL_IMAGESV1="${BASEURL/iam/ims}/v1/cloudimages"
+	AUTH_URL_IMAGESV2="${BASEURL/iam/ims}/v2/cloudimages"
 
 	AUTH_URL_FLAVORS="${BASEURL/iam/ecs}/v1/$OS_PROJECT_ID/cloudservers/flavors"
 	AUTH_URL_KEYNAMES="${BASEURL/iam/ecs}/v2/$OS_PROJECT_ID/os-keypairs"
@@ -479,7 +480,9 @@ printHelp() {
    echo "   --min-disk     <GB>"
    echo "   --min-ram      <MB>          # optional (default 1024)"
    echo "   --os-version   <os_version>  # optional (default Other)"
-   echo "   --property     <key=val>     # optional properties"
+   echo "   --property     <key=val>     # optional properties (multiple times possible)"
+   echo "otc images register NAME FILE   # create (private) image with name and s3 file"
+   echo "   --property, --min-disk, --os-version and --wait supported"
    echo "otc images update <id>          # change properties, --image-name, min-*"
    echo "otc images delete <id>          # delete (private) image by ID"
    echo
@@ -920,7 +923,36 @@ getIMAGEDetail() {
 	if ! is_uuid "$1"; then convertIMAGENameToId "$1"; else IMAGE_ID="$1"; fi
 	#curlgetauth $TOKEN "$AUTH_URL_IMAGES?limit=160"| jq '.images[] | select(.id == "'$IMAGE_ID'")'
 	curlgetauth $TOKEN "$AUTH_URL_IMAGES/$IMAGE_ID"| jq '.'
-#| python -m json.tool
+}
+
+registerIMAGE() {
+	if test -z "$1"; then echo "ERROR: Need to specify NAME"; exit 2; fi
+	if test -z "$2"; then echo "ERROR: Need to specify OBSBucket"; exit 2; fi
+	if test -z "$MINDISK"; then echo "ERROR: Need to specify --min-disk"; exit 2; fi
+	if test -z "$MINRAM"; then MINRAM=1024; fi
+	if test -z "$DISKFORMAT"; then DISKFORMAT="${2##.*}"; fi
+	if test -z "$DISKFORMAT" -o "$DISKFORMAT" = "zvhd"; then DISKFORMAT="vhd"; fi
+	unset OSVJSON
+	if test -n "$OSVERSION"; then OSVJSON="\"os_version\": \"$OSVERSION\","; fi
+	OLDIFS="$IFS"; IFS=","
+	for prop in $PROPS; do
+		val="${prop##*=}"
+		case $val in
+			[0-9]*|false|False|true|True)
+				pstr=`echo "$prop" | sed 's/^_*\([^=]*\)=\(.*\)$/"\1": \2/'`
+				;;
+			*)
+				pstr=`echo "$prop" | sed 's/^_*\([^=]*\)=\(.*\)$/"\1": "\2"/'`
+				;;
+		esac
+		OSVJSON="$OSVJSON $pstr,"
+	done < <( echo "$PROPS")
+	IFS="$OLDIFS"
+	REQ="{ $OSVJSON  \"min_disk\": $MINDISK, \"min_ram\": $MINRAM,
+		\"disk_format\": \"$DISKFORMAT\", \"name\": \"$1\", \"image_url\": \"$2\" }"
+	IMGTASKID=`curlpostauth $TOKEN "$REQ" "$AUTH_URL_IMAGESV2/action" | jq '.job_id' | cut -d':' -f 2 | tr -d '" '`
+   WaitForTask $IMGTASKID 5
+   
 }
 
 createIMAGE() {
@@ -1668,7 +1700,7 @@ MAINCOM=$1; shift
 SUBCOM=$1; shift
 
 #if [ "$MAINCOM" == "ecs" ] && [ "$SUBCOM" == "create" ] || [ "$MAINCOM" == "vpc" ] && [ "$SUBCOM" == "create" ];then
-if [ "$SUBCOM" == "create" -o "$SUBCOM" == "update" ]; then
+if [ "$SUBCOM" == "create" -o "$SUBCOM" == "update" -o "$SUBCOM" == "register" ]; then
 	while [[ $# > 0 ]]
 	do
 		key="$1"
@@ -2083,11 +2115,13 @@ elif [ "$MAINCOM" == "images" ] && [ "$SUBCOM" == "upload" ]; then
 	fi
 
 elif [ "$MAINCOM" == "images" ] && [ "$SUBCOM" == "create" ]; then
-   createIMAGE $1
+   createIMAGE "$1"
+elif [ "$MAINCOM" == "images" ] && [ "$SUBCOM" == "register" ]; then
+   registerIMAGE "$1" "$2"
 elif [ "$MAINCOM" == "images" ] && [ "$SUBCOM" == "delete" ]; then
 	for img in "$@"; do deleteIMAGE $img; done
 elif [ "$MAINCOM" == "images" ] && [ "$SUBCOM" == "update" ]; then
-	updateIMAGE $1
+	updateIMAGE "$1"
 
 elif [ "$MAINCOM" == "ecs" ] && [ "$SUBCOM" == "flavor-list" ];then
    getFLAVORList
