Added command "rds list".
Added configuration variable OS_USER_DOMAIN_ID. If not set
in environment, it is determined from IAM REST response.
In OTC 1.01, RDS instances are associated to domains instead
of projects. This is a known issue and planned to be changed
to stay compatible with the managment model used in Trove API.

diff --git a/otc b/otc
--- a/otc
+++ b/otc
@@ -205,6 +205,13 @@ getIamToken() {
 		echo "ERROR: Failed to authenticate and get token from $IAM_AUTH_URL for user $OS_USERNAME"
 		exit 2
 	fi
+	if test -z "$OS_USER_DOMAIN_ID"; then
+		OS_USER_DOMAIN_ID=`echo "$IAMRESP" | getUserDomainIdFromIamResponse `
+	fi
+	if test -z "$OS_USER_DOMAIN_ID"; then
+		echo "ERROR: Failed to determine user domain id from $IAM_AUTH_URL for user $OS_USERNAME"
+		exit 2
+	fi
 
 	# SET ENDPOINTS
 	# TODO: Parse catalog instead
@@ -235,10 +242,8 @@ getIamToken() {
 	AUTH_URL_ELB="${BASEURL/iam/elb}/v1.0/$OS_PROJECT_ID/elbaas"
 	AUTH_URL_ELB_LB="$AUTH_URL_ELB/loadbalancers"
 
-	AUTH_URL_RDS="${BASEURL/iam/rds}/rds/v1/$OS_PROJECT_ID/instances"
+	AUTH_URL_RDS="${BASEURL/iam/rds}/rds/v1/$OS_USER_DOMAIN_ID/instances"
 	AUTH_URL_RDS="${AUTH_URL_RDS/:443\///}" # remove :443 port when present
-	# AUTH_URL_RDS="https://rds.eu-de.otc.t-systems.com/rds/v1/$OS_PROJECT_ID/instances"
-	# export IAM_AUTH_URL="https://iam.eu-de.otc.t-systems.com/v3/auth/tokens"
 }
 
 getECSVM() {
@@ -955,6 +960,10 @@ WaitForTask() {
 # Does not seem to work :-(
 DeleteTask() {
 	curldeleteauth "$TOKEN" "$AUTH_URL_ECS_JOB/$1"
+}
+
+getUserDomainIdFromIamResponse() {
+	tail -n1 | jq -r .token.user.domain.id
 }
 
 ##########################################################################################
