Add ability to create image from VM (cricketlong).
Streamline parameter handling as compared to PR21.
Description is optional, for both modes of images create.

diff --git a/otc b/otc
--- a/otc
+++ b/otc
@@ -521,7 +521,6 @@ printHelp() {
    echo "otc evs attach --name ecsname  device:volume      # use names instead of ids"
    echo "otc evs detach        ecsid   [device:]volumeid   # detach volume-id from ecs"
    echo "otc evs detach --name ecsname [device:]volume     # use names instead of ids"
-   echo
    #TODO volume change ...
    echo
    echo "--- Virtual Private Network ---"
@@ -582,6 +581,9 @@ printHelp() {
    echo "   --min-ram      <MB>          # optional (default 1024)"
    echo "   --os-version   <os_version>  # optional (default Other)"
    echo "   --property     <key=val>     # optional properties (multiple times possible)"
+   echo "otc images create NAME          # create image from ECS instance (snapshot)"
+   echo "   --instance-id  <instance id>"
+   echo "   --description  <description> # optional"
    echo "otc images register NAME FILE   # create (private) image with name and s3 file"
    echo "   --property, --min-disk, --os-version and --wait supported"
    echo "otc images update <id>          # change properties, --image-name, min-*"
@@ -1095,9 +1097,10 @@ registerIMAGE() {
 
 createIMAGE() {
 	if test -z "$DISKFORMAT"; then DISKFORMAT="vhd"; fi
-	if test -z "$MINDISK"; then echo "ERROR: Need to specify --min-disk" 1>&2; exit 2; fi
+	if test -z "$MINDISK" -a -z "$INSTANCE_ID"; then echo "ERROR: Need to specify --min-disk OR --instance-id" 1>&2; exit 2; fi
 	if test -z "$MINRAM"; then MINRAM=1024; fi
-	if test -z "$1"; then echo "ERROR: Need to specify NAME" 1>&2; exit 2; fi
+	if test -n "$1"; then IMAGENAME="$1"; fi
+	if test -z "IMAGENAME"; then echo "ERROR: Need to specify NAME" 1>&2; exit 2; fi
 	unset OSVJSON
 	if test -n "$OSVERSION"; then OSVJSON="\"__os_version\": \"$OSVERSION\","; fi
 	OLDIFS="$IFS"; IFS=","
@@ -1114,10 +1117,17 @@ createIMAGE() {
 		OSVJSON="$OSVJSON $pstr,"
 	done < <( echo "$PROPS")
 	IFS="$OLDIFS"
-	REQ="{ $OSVJSON  \"container_format\": \"bare\",
-		\"disk_format\": \"$DISKFORMAT\", \"min_disk\": $MINDISK,
-		\"min_ram\": $MINRAM, \"name\": \"$1\",
-		\"visibility\": \"private\", \"protected\": false }"
+   if test -z "$INSTANCE_ID"; then
+		# Create fresh image
+		REQ="{ $OSVJSON  \"container_format\": \"bare\",
+			\"disk_format\": \"$DISKFORMAT\", \"min_disk\": $MINDISK,
+			\"min_ram\": $MINRAM, \"name\": \"$IMAGENAME\",
+			\"visibility\": \"private\", \"protected\": false }"
+	else
+		# Create VM snapshot image
+		REQ="{ \"name\": \"$IMAGENAME\", \"instance_id\": \"$INSTANCE_ID\" }"
+	fi
+   if test -n "$DESCRIPTION"; then REQ="${REQ%\}}, \"description\": \"$DESCRIPTION\" }"; fi
 	curlpostauth $TOKEN "$REQ" "$AUTH_URL_IMAGES" | jq '.' #'.[]'
 }
 
@@ -1971,7 +1981,7 @@ MAINCOM=$1; shift
 SUBCOM=$1; shift
 
 #if [ "$MAINCOM" == "ecs" ] && [ "$SUBCOM" == "create" ] || [ "$MAINCOM" == "vpc" ] && [ "$SUBCOM" == "create" ];then
-if [ "$SUBCOM" == "create" -o "$SUBCOM" == "update" -o "$SUBCOM" == "register" -o "$SUBCOM" == "download" -o "$SUBCOM" == "snapshot" ] || [[ "$SUBCOM" == *-instances ]]; then
+if [ "$SUBCOM" == "create" -o "$SUBCOM" == "update" -o "$SUBCOM" == "register" -o "$SUBCOM" == "download" ] || [[ "$SUBCOM" == *-instances ]]; then
 	while [[ $# > 0 ]]
 	do
 		key="$1"
@@ -1983,6 +1993,10 @@ if [ "$SUBCOM" == "create" -o "$SUBCOM" == "update" -o "$SUBCOM" == "register" -
 			;;
 			-n|--instance-name)
 			INSTANCE_NAME="$2"
+			shift # past argument
+			;;
+			-t|--instance-id)
+			INSTANCE_ID="$2"
 			shift # past argument
 			;;
 			--volume-name)
@@ -2166,6 +2180,10 @@ if [ "$SUBCOM" == "create" -o "$SUBCOM" == "update" -o "$SUBCOM" == "register" -
 			;;
 			--property)
 			if test -z "$PROPS"; then PROPS="$2"; else PROPS="$PROPS,$2"; fi
+			shift
+			;;
+			--description)
+			DESCRIPTION="$2"
 			shift
 			;;
 			-*)
